/// Flutter icons AppIcons_1
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons_1
///      fonts:
///       - asset: fonts/AppIcons_1.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons_1 {
  AppIcons_1._();

  static const _kFontFam = 'AppIcons_1';
  static const _kFontPkg = null;

  static const IconData cricketicon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData europaleague = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData footballicon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData humaaans = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData la_liga = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData matchday2 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData matchday4 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData matchresult2 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData matchresult4 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuicon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobilelady = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData premier_league_logo_wine = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selecticon = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seria_a = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sidemenuimage = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData splashcrowdicon = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData splashgroundicon = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tournament2 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
